import Link from "next/link";
import { BreadcrumbJsonLd } from "@/components/seo/BreadcrumbJsonLd";
import { PageBreadcrumbs } from "@/components/seo/PageBreadcrumbs";
import { RelatedResources } from "@/components/seo/RelatedResources";
import { buildCtrMetadata, CTR_TERMS } from "@/lib/seo/ctr-metadata";

export const metadata = buildCtrMetadata(CTR_TERMS, {
  canonical: "/terms",
});

export default function TermsPage() {
  return (
    <>
      <BreadcrumbJsonLd
        items={[
          { name: "Home", path: "/" },
          { name: "Terms of Service", path: "/terms" },
        ]}
      />
    <div className="container-prose py-16">
      <PageBreadcrumbs
        items={[
          { name: "Home", path: "/" },
          { name: "Terms of Service", path: "/terms" },
        ]}
      />
      <p className="section-eyebrow mt-8">Legal</p>
      <h1 className="mt-6 font-display text-4xl font-bold tracking-tight text-slate-900 sm:text-5xl">
        Terms of Service
      </h1>
      <p className="mt-3 text-sm text-slate-500">Last updated: April 30, 2026</p>
      <div className="mt-10 space-y-8 text-slate-700">
        <Section title="1. Agreement">
          By using ResumeIQ, you agree to these terms. If you don&apos;t,
          please don&apos;t use the product.
        </Section>
        <Section title="2. What ResumeIQ does">
          ResumeIQ extracts text from resume files you upload (PDF or DOCX),
          scores them with AI, and returns suggestions. It does not
          guarantee employment outcomes, ATS pass rates, or compatibility
          with every employer system on Earth. Use it as one signal of
          many.
        </Section>
        <Section title="3. Acceptable use">
          You won&apos;t misuse the service, attempt to disrupt
          infrastructure, upload malware, or violate applicable law. You
          confirm you have the right to upload the files you submit (e.g.,
          your own resume, or one you&apos;re permitted to review).
        </Section>
        <Section title="4. AI output disclaimer">
          AI suggestions are generated by language models and may
          occasionally be incorrect, biased, or outdated. Always sanity-check
          rewrites and keyword recommendations before applying them to your
          resume.
        </Section>
        <Section title="5. No warranties">
          The service is provided &ldquo;as is&rdquo; without warranties of any
          kind. To the maximum extent permitted by law, we disclaim
          liability for indirect or consequential damages arising from use
          of the service.
        </Section>
        <Section title="6. Changes">
          We may update these terms; continued use after changes counts as
          acceptance of the revised terms. Material changes will be flagged
          with an updated date at the top of this page.
        </Section>
      </div>
      <p className="mt-10 text-sm text-slate-500">
        See also{" "}
        <Link href="/privacy" className="font-semibold text-[#16a34a] underline underline-offset-2">
          Privacy Policy
        </Link>{" "}
        and{" "}
        <Link href="/contact" className="font-semibold text-[#16a34a] underline underline-offset-2">
          Contact
        </Link>
        .
      </p>
      <RelatedResources path="/terms" excludeHref="/terms" />
    </div>
    </>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="text-xl font-semibold text-slate-900">{title}</h2>
      <p className="mt-3 leading-relaxed">{children}</p>
    </section>
  );
}
